Main svc
AlbinaKuznetsova/java-explore-with-me pull request #2
Opened 2024-07-08 11:11 UTC by AlbinaKuznetsova

2024-07-08 21:00 UTC, andrew-larkin requested changes
Привет! Действительно качественная большая работа проделана, по архитектуре у меня вопросов нет. Остается местами внести небольшие правки и будем готовы двигаться дальше.

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/category/controllers/CategoryAdminController.java
> +    public ResponseEntity<?> deleteCategory(@PathVariable int catId) {
вместо ? можно использовать класс Void. Также, не рекомендую использовать примитивы в аргументах методов контроллеров - так мы можем сразу словить NPE. предлагаю заменить их на врапперы (int -> Integer)

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/category/model/Category.java
> +@Data
для моделей-сущностей лучше не использовать @Data, т.к. она может некорректно рассчитывать хэш. Лучше заменить ее на @Getter, @Setter и т.д.

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/event/dto/Location.java
> +public class Location {
давай переместим ее в папку к моделям

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/event/repository/EventRepository.java
> +    Event findByIdAndInitiatorId(Integer id, Integer initiatorId);
не стоит возвращать "голые" объекты из репозитория, может получиться так, что вернется null. лучше оформить это как Optional<Event>, а уже непосредственно в сервисе доставать объект из optional с помощью метода .orElseThrow()

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/event/repository/EventRepository.java
> +    @Query(value = " select * from events as ev " +
нативные запросы - нормальное решение, но может возникнуть проблема (из-за разницы синтаксиса), если вдруг понадобится поменять postgres на другую БД. Оптимальное решение - использовать jpql. но это опционально, можно оставить как есть, а выполнять только если у тебя остается на это время

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/request/model/ParticipationRequest.java
> +    private Integer event;
тут, наверное, стоит добавить именно Event

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/request/model/ParticipationRequest.java
> +    private Integer requester;
а тут - User

2024-07-08 21:00 UTC, andrew-larkin commented on main/src/main/java/ru/yandex/practicum/request/repository/RequestRepository.java
> +    ParticipationRequest findByRequesterAndEvent(Integer userId, Integer eventId);
optional

2024-07-09 11:24 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/category/controllers/CategoryAdminController.java
> +    public ResponseEntity<?> deleteCategory(@PathVariable int catId) {
Исправила

2024-07-09 11:28 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/category/model/Category.java
> +@Data
Исправила

2024-07-09 11:30 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/event/dto/Location.java
> +public class Location {
исправила

2024-07-09 11:37 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/event/repository/EventRepository.java
> +    Event findByIdAndInitiatorId(Integer id, Integer initiatorId);
Исправила

2024-07-09 11:43 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/request/repository/RequestRepository.java
> +    ParticipationRequest findByRequesterAndEvent(Integer userId, Integer eventId);
Исправила

2024-07-09 11:53 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/request/model/ParticipationRequest.java
> +    private Integer event;
Исправила

2024-07-09 11:53 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/request/model/ParticipationRequest.java
> +    private Integer requester;
Исправила

2024-07-09 13:13 UTC, AlbinaKuznetsova commented on main/src/main/java/ru/yandex/practicum/event/repository/EventRepository.java
> +    @Query(value = " select * from events as ev " +
Заменила на JPQL

2024-07-10 08:41 UTC, merged